package com.emfitsolutions.gopreach.data.export

import android.content.Context
import android.content.Intent
import androidx.core.content.FileProvider
import com.emfitsolutions.gopreach.data.print.OrientationMode
import com.emfitsolutions.gopreach.data.print.PrintOptions
import com.emfitsolutions.gopreach.data.print.ReportPrinter
import java.io.ByteArrayOutputStream
import java.io.File
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream

/** Everything a printed / Excel Congregation Comparative Report contains, already formatted as text (so both outputs match the screen exactly). */
data class ComparativeReportData(
    val congregationName: String,
    val periodA: String,
    val periodB: String,
    val generatedBy: String,
    val generatedAt: String,
    val calculationMode: String,
    /** First row = headings (Statistic | Period A | Period B | Difference | % Change). */
    val comparison: List<List<String>>,
    /** First row = headings (Statistic | Jan 2025 | ...). */
    val monthly: List<List<String>>,
    /** Meeting attendance coverage lines (recorded / missing per period) and the months that have no snapshot. */
    val notes: List<String>,
    /** Formal-report details (report number, status, submitted by / date, Circuit Overseer, received date, CO remarks), shown under the header. */
    val details: List<Pair<String, String>> = emptyList(),
    /** Months of the periods that have no historical snapshot. */
    val missingMonths: List<String> = emptyList(),
    /** The end-of-report summary (first row = headings), always printed last. */
    val summary: List<List<String>> = emptyList(),
)

/** Print / PDF (through the zoomable print preview) and Excel of the Congregation Comparative Report, in a compact landscape layout. */
object ComparativeStatisticsExporter {

    fun print(context: Context, data: ComparativeReportData) {
        fun e(s: String) = ReportPrinter.escapeHtml(s)
        fun table(rows: List<List<String>>, firstColWide: Boolean = true) = buildString {
            append("<table><thead><tr>")
            rows.first().forEachIndexed { i, h -> append("<th").append(if (i == 0) " class=\"l\"" else "").append(">").append(e(h)).append("</th>") }
            append("</tr></thead><tbody>")
            rows.drop(1).forEach { r ->
                append("<tr>")
                r.forEachIndexed { i, c -> append("<td").append(if (i == 0) " class=\"l\"" else "").append(">").append(e(c)).append("</td>") }
                append("</tr>")
            }
            append("</tbody></table>")
        }
        val html = buildString {
            append("<html><head><meta charset=\"utf-8\"><style>")
            append("@page{size:landscape;margin:8mm} body{font-family:sans-serif;font-size:10px;} h1{margin:0;font-size:15px} h2{margin:10px 0 4px 0;font-size:12px}")
            append(".sub{font-size:13px;font-weight:bold;margin:0 0 4px 0} .meta div{margin:1px 0}")
            append("table{border-collapse:collapse;width:100%;margin-bottom:4px} th,td{border:1px solid #000;padding:2px 5px;text-align:right} th{background:#e6e6e6}")
            append("td.l,th.l{text-align:left;white-space:nowrap} tr{page-break-inside:avoid} .note{margin:1px 0;color:#333}")
            append("</style></head><body><h1>GoPreach App</h1><p class=\"sub\">Congregation Comparative Report</p><div class=\"meta\">")
            append("<div><b>Congregation:</b> ").append(e(data.congregationName)).append("</div>")
            append("<div><b>Period A:</b> ").append(e(data.periodA)).append(" &nbsp; <b>Period B:</b> ").append(e(data.periodB)).append("</div>")
            append("<div><b>Generated By:</b> ").append(e(data.generatedBy)).append(" &nbsp; <b>Generated:</b> ").append(e(data.generatedAt))
            append(" &nbsp; <b>Attendance Calculation:</b> ").append(e(data.calculationMode)).append("</div>")
            data.details.forEach { (k, v) -> append("<div><b>").append(e(k)).append(":</b> ").append(e(v)).append("</div>") }
            append("</div>")
            append("<h2>Period Comparison</h2>").append(table(data.comparison))
            data.notes.forEach { append("<div class=\"note\">").append(e(it)).append("</div>") }
            if (data.missingMonths.isNotEmpty()) append("<div class=\"note\"><b>Missing data:</b> ").append(e(data.missingMonths.joinToString(", "))).append("</div>")
            append("<h2>Monthly Historical Statistics</h2>").append(table(data.monthly))
            if (data.summary.isNotEmpty()) append("<h2>Summary</h2>").append(table(data.summary))
            append("<div class=\"note\">Generated By: ").append(e(data.generatedBy)).append(" &nbsp; Generated: ").append(e(data.generatedAt)).append("</div>")
            append("</body></html>")
        }
        ReportPrinter.printHtml(context, "Congregation Comparative Report - ${data.congregationName}", html, PrintOptions(OrientationMode.LANDSCAPE))
    }

    fun shareExcel(context: Context, data: ComparativeReportData) {
        fun esc(s: String) = s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("\"", "&quot;")
        fun col(i: Int): String { var n = i; var s = ""; do { s = ('A' + n % 26) + s; n = n / 26 - 1 } while (n >= 0); return s }
        val xml = StringBuilder()
        var r = 0
        fun cell(c: Int, v: String, style: Int) = "<c r=\"${col(c)}$r\" s=\"$style\" t=\"inlineStr\"><is><t xml:space=\"preserve\">${esc(v)}</t></is></c>"
        fun row(cells: List<String>, style: Int = 0, firstStyle: Int = style) { r++; xml.append("<row r=\"$r\">"); cells.forEachIndexed { i, v -> xml.append(cell(i, v, if (i == 0) firstStyle else style)) }; xml.append("</row>") }
        fun blank() { r++ }
        row(listOf("GoPreach App"), 1)
        row(listOf("Congregation Comparative Report"), 1)
        row(listOf("Congregation:", data.congregationName), 0, 1)
        row(listOf("Period A:", data.periodA), 0, 1)
        row(listOf("Period B:", data.periodB), 0, 1)
        row(listOf("Generated By:", data.generatedBy), 0, 1)
        row(listOf("Generated:", data.generatedAt), 0, 1)
        row(listOf("Attendance Calculation:", data.calculationMode), 0, 1)
        data.details.forEach { (k, v) -> row(listOf("$k:", v), 0, 1) }
        blank()
        row(listOf("Period Comparison"), 1)
        row(data.comparison.first(), 2)
        data.comparison.drop(1).forEach { row(it, 0, 1) }
        data.notes.forEach { row(listOf(it)) }
        if (data.missingMonths.isNotEmpty()) row(listOf("Missing data:", data.missingMonths.joinToString(", ")), 0, 1)
        blank()
        row(listOf("Monthly Historical Statistics"), 1)
        row(data.monthly.first(), 2)
        data.monthly.drop(1).forEach { row(it, 0, 1) }
        if (data.summary.isNotEmpty()) {
            blank()
            row(listOf("Summary"), 1)
            row(data.summary.first(), 2)
            data.summary.drop(1).forEach { row(it, 0, 1) }
        }
        val cols = (0 until data.monthly.first().size.coerceAtLeast(5)).joinToString("") { i -> "<col min=\"${i + 1}\" max=\"${i + 1}\" width=\"${if (i == 0) 30 else 14}\" customWidth=\"1\"/>" }
        val sheet = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><worksheet xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\"><cols>$cols</cols><sheetData>$xml</sheetData></worksheet>"
        val styles = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><styleSheet xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\">" +
            "<fonts count=\"2\"><font><sz val=\"11\"/><name val=\"Calibri\"/></font><font><b/><sz val=\"11\"/><name val=\"Calibri\"/></font></fonts>" +
            "<fills count=\"3\"><fill><patternFill patternType=\"none\"/></fill><fill><patternFill patternType=\"gray125\"/></fill>" +
            "<fill><patternFill patternType=\"solid\"><fgColor rgb=\"FFD9E1F2\"/></patternFill></fill></fills>" +
            "<borders count=\"1\"><border><left/><right/><top/><bottom/><diagonal/></border></borders>" +
            "<cellStyleXfs count=\"1\"><xf numFmtId=\"0\" fontId=\"0\" fillId=\"0\" borderId=\"0\"/></cellStyleXfs>" +
            "<cellXfs count=\"3\"><xf numFmtId=\"0\" fontId=\"0\" fillId=\"0\" borderId=\"0\" xfId=\"0\"/>" +
            "<xf numFmtId=\"0\" fontId=\"1\" fillId=\"0\" borderId=\"0\" xfId=\"0\" applyFont=\"1\"/>" +
            "<xf numFmtId=\"0\" fontId=\"1\" fillId=\"2\" borderId=\"0\" xfId=\"0\" applyFont=\"1\" applyFill=\"1\"/></cellXfs></styleSheet>"
        val bytes = ByteArrayOutputStream().also { out ->
            ZipOutputStream(out).use { zip ->
                fun put(name: String, content: String) { zip.putNextEntry(ZipEntry(name)); zip.write(content.toByteArray(Charsets.UTF_8)); zip.closeEntry() }
                put("[Content_Types].xml", "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\">" +
                    "<Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/><Default Extension=\"xml\" ContentType=\"application/xml\"/>" +
                    "<Override PartName=\"/xl/workbook.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml\"/>" +
                    "<Override PartName=\"/xl/worksheets/sheet1.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml\"/>" +
                    "<Override PartName=\"/xl/styles.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml\"/></Types>")
                put("_rels/.rels", "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\">" +
                    "<Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument\" Target=\"xl/workbook.xml\"/></Relationships>")
                put("xl/workbook.xml", "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><workbook xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\" " +
                    "xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\"><sheets><sheet name=\"Comparative Report\" sheetId=\"1\" r:id=\"rId1\"/></sheets></workbook>")
                put("xl/_rels/workbook.xml.rels", "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\">" +
                    "<Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet\" Target=\"worksheets/sheet1.xml\"/>" +
                    "<Relationship Id=\"rId2\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles\" Target=\"styles.xml\"/></Relationships>")
                put("xl/styles.xml", styles)
                put("xl/worksheets/sheet1.xml", sheet)
            }
        }.toByteArray()
        val dir = File(context.cacheDir, "exports").apply { mkdirs() }
        val label = data.congregationName.replace(Regex("[^A-Za-z0-9]+"), "_").trim('_').ifBlank { "Congregation" }
        val file = File(dir, "ComparativeReport_$label.xlsx").apply { writeBytes(bytes) }
        val uri = FileProvider.getUriForFile(context, "${context.packageName}.fileprovider", file)
        val intent = Intent(Intent.ACTION_SEND).apply {
            type = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
            putExtra(Intent.EXTRA_STREAM, uri)
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
        context.startActivity(Intent.createChooser(intent, "Share Congregation Comparative Report"))
    }
}
