package com.emfitsolutions.gopreach.data.export

import android.content.Context
import android.content.Intent
import androidx.core.content.FileProvider
import com.emfitsolutions.gopreach.data.print.OrientationMode
import com.emfitsolutions.gopreach.data.print.PrintOptions
import com.emfitsolutions.gopreach.data.print.ReportPrinter
import java.io.ByteArrayOutputStream
import java.io.File
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream

/**
 * A report in the Universal Report layout, already formatted as text: header, the records table, then the mandatory end-of-report
 * Summary. Print / PDF and Excel are both produced from this one object, so they show exactly what the screen showed.
 */
data class TableReportData(
    val title: String,
    /** Header lines under the title: congregation, reporting period, status, ... */
    val details: List<Pair<String, String>>,
    val recordsFound: String,
    /** First row = headings. */
    val table: List<List<String>>,
    /** First row = headings (Metric | Value). Always printed last. */
    val summary: List<List<String>>,
    val generatedBy: String,
    val generatedAt: String,
    val landscape: Boolean = true,
)

object TableReportExporter {
    private fun e(s: String) = ReportPrinter.escapeHtml(s)

    fun html(data: TableReportData): String = buildString {
        append("<html><head><meta charset=\"utf-8\"><style>")
        append("@page{size:").append(if (data.landscape) "landscape" else "portrait").append(";margin:8mm} body{font-family:sans-serif;font-size:10px;} h1{margin:0;font-size:15px} h2{margin:10px 0 4px 0;font-size:12px}")
        append(".sub{font-size:13px;font-weight:bold;margin:0 0 4px 0} .meta div{margin:1px 0}")
        append("table{border-collapse:collapse;width:100%;margin-bottom:4px} th,td{border:1px solid #000;padding:2px 5px;text-align:center} th{background:#e6e6e6}")
        append("td.l,th.l{text-align:left} tr{page-break-inside:avoid} .note{margin:1px 0;color:#333} table.sum{width:auto} table.sum td.v{text-align:right;font-weight:bold}")
        append("</style></head><body><h1>GoPreach App</h1><p class=\"sub\">").append(e(data.title)).append("</p><div class=\"meta\">")
        data.details.forEach { (k, v) -> append("<div><b>").append(e(k)).append(":</b> ").append(e(v)).append("</div>") }
        append("<div><b>Records Found:</b> ").append(e(data.recordsFound)).append(" &nbsp; <b>Generated:</b> ").append(e(data.generatedAt)).append("</div></div>")
        append("<table><thead><tr>")
        data.table.first().forEachIndexed { i, h -> append("<th").append(if (i == 0) " class=\"l\"" else "").append(">").append(e(h)).append("</th>") }
        append("</tr></thead><tbody>")
        data.table.drop(1).forEach { r ->
            append("<tr>")
            r.forEachIndexed { i, c -> append("<td").append(if (i == 0) " class=\"l\"" else "").append(">").append(e(c)).append("</td>") }
            append("</tr>")
        }
        append("</tbody></table>")
        append("<h2>Summary</h2><table class=\"sum\">")
        data.summary.drop(1).forEach { r -> append("<tr><td class=\"l\">").append(e(r[0])).append("</td><td class=\"v\">").append(e(r[1])).append("</td></tr>") }
        append("</table><div class=\"note\">Generated By: ").append(e(data.generatedBy)).append(" &nbsp; Generated Date/Time: ").append(e(data.generatedAt)).append("</div>")
        append("</body></html>")
    }

    fun print(context: Context, data: TableReportData) =
        ReportPrinter.printHtml(context, data.title, html(data), PrintOptions(if (data.landscape) OrientationMode.LANDSCAPE else OrientationMode.PORTRAIT))

    fun shareExcel(context: Context, data: TableReportData) {
        fun esc(s: String) = s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("\"", "&quot;")
        fun col(i: Int): String { var n = i; var s = ""; do { s = ('A' + n % 26) + s; n = n / 26 - 1 } while (n >= 0); return s }
        val xml = StringBuilder()
        var r = 0
        fun cell(c: Int, v: String, style: Int) = "<c r=\"${col(c)}$r\" s=\"$style\" t=\"inlineStr\"><is><t xml:space=\"preserve\">${esc(v)}</t></is></c>"
        fun row(cells: List<String>, style: Int = 0, firstStyle: Int = style) { r++; xml.append("<row r=\"$r\">"); cells.forEachIndexed { i, v -> xml.append(cell(i, v, if (i == 0) firstStyle else style)) }; xml.append("</row>") }
        fun blank() { r++ }
        row(listOf("GoPreach App"), 1)
        row(listOf(data.title), 1)
        data.details.forEach { (k, v) -> row(listOf("$k:", v), 0, 1) }
        row(listOf("Records Found:", data.recordsFound), 0, 1)
        row(listOf("Generated:", data.generatedAt), 0, 1)
        blank()
        row(data.table.first(), 2)
        data.table.drop(1).forEach { row(it, 0, 1) }
        blank()
        row(listOf("Summary"), 1)
        data.summary.drop(1).forEach { row(it, 0, 1) }
        blank()
        row(listOf("Generated By:", data.generatedBy), 0, 1)
        row(listOf("Generated Date/Time:", data.generatedAt), 0, 1)
        val cols = (0 until data.table.first().size.coerceAtLeast(2)).joinToString("") { i -> "<col min=\"${i + 1}\" max=\"${i + 1}\" width=\"${if (i == 0) 30 else 16}\" customWidth=\"1\"/>" }
        val sheet = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><worksheet xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\"><cols>$cols</cols><sheetData>$xml</sheetData></worksheet>"
        val styles = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><styleSheet xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\">" +
            "<fonts count=\"2\"><font><sz val=\"11\"/><name val=\"Calibri\"/></font><font><b/><sz val=\"11\"/><name val=\"Calibri\"/></font></fonts>" +
            "<fills count=\"3\"><fill><patternFill patternType=\"none\"/></fill><fill><patternFill patternType=\"gray125\"/></fill>" +
            "<fill><patternFill patternType=\"solid\"><fgColor rgb=\"FFD9E1F2\"/></patternFill></fill></fills>" +
            "<borders count=\"1\"><border><left/><right/><top/><bottom/><diagonal/></border></borders>" +
            "<cellStyleXfs count=\"1\"><xf numFmtId=\"0\" fontId=\"0\" fillId=\"0\" borderId=\"0\"/></cellStyleXfs>" +
            "<cellXfs count=\"3\"><xf numFmtId=\"0\" fontId=\"0\" fillId=\"0\" borderId=\"0\" xfId=\"0\"/>" +
            "<xf numFmtId=\"0\" fontId=\"1\" fillId=\"0\" borderId=\"0\" xfId=\"0\" applyFont=\"1\"/>" +
            "<xf numFmtId=\"0\" fontId=\"1\" fillId=\"2\" borderId=\"0\" xfId=\"0\" applyFont=\"1\" applyFill=\"1\"/></cellXfs></styleSheet>"
        val bytes = ByteArrayOutputStream().also { out ->
            ZipOutputStream(out).use { zip ->
                fun put(name: String, content: String) { zip.putNextEntry(ZipEntry(name)); zip.write(content.toByteArray(Charsets.UTF_8)); zip.closeEntry() }
                put("[Content_Types].xml", "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\">" +
                    "<Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/><Default Extension=\"xml\" ContentType=\"application/xml\"/>" +
                    "<Override PartName=\"/xl/workbook.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml\"/>" +
                    "<Override PartName=\"/xl/worksheets/sheet1.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml\"/>" +
                    "<Override PartName=\"/xl/styles.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml\"/></Types>")
                put("_rels/.rels", "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\">" +
                    "<Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument\" Target=\"xl/workbook.xml\"/></Relationships>")
                put("xl/workbook.xml", "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><workbook xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\" " +
                    "xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\"><sheets><sheet name=\"Report\" sheetId=\"1\" r:id=\"rId1\"/></sheets></workbook>")
                put("xl/_rels/workbook.xml.rels", "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\">" +
                    "<Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet\" Target=\"worksheets/sheet1.xml\"/>" +
                    "<Relationship Id=\"rId2\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles\" Target=\"styles.xml\"/></Relationships>")
                put("xl/styles.xml", styles)
                put("xl/worksheets/sheet1.xml", sheet)
            }
        }.toByteArray()
        val dir = File(context.cacheDir, "exports").apply { mkdirs() }
        val label = data.title.replace(Regex("[^A-Za-z0-9]+"), "_").trim('_').ifBlank { "Report" }
        val file = File(dir, "$label.xlsx").apply { writeBytes(bytes) }
        val uri = FileProvider.getUriForFile(context, "${context.packageName}.fileprovider", file)
        val intent = Intent(Intent.ACTION_SEND).apply {
            type = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
            putExtra(Intent.EXTRA_STREAM, uri)
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
        context.startActivity(Intent.createChooser(intent, "Share " + data.title))
    }
}
