package com.emfitsolutions.gopreach.data.local.dao

import androidx.room.Dao
import androidx.room.Delete
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import com.emfitsolutions.gopreach.data.local.PendingSyncOperationEntity
import kotlinx.coroutines.flow.Flow

@Dao
interface SyncQueueDao {
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun enqueue(operation: PendingSyncOperationEntity): Long

    /** Only the rows [SyncWorker][com.emfitsolutions.gopreach.data.sync
     * .SyncWorker] should actually attempt — excludes anything already
     * flagged [PendingSyncOperationEntity.isPermanentFailure] (see that
     * column's own doc comment for why: a permanent failure retried forever
     * alongside everything else is what used to keep the whole sync system
     * looking "stuck" long after connectivity, and every other pending
     * change, was fine). */
    @Query("SELECT * FROM pending_sync_operations WHERE isPermanentFailure = 0 ORDER BY createdAt ASC")
    suspend fun getAllPending(): List<PendingSyncOperationEntity>

    /** Drives the "pending sync" indicator (spec §6.5) app-wide — genuinely
     * retryable rows only (see [getAllPending]); a permanent failure is
     * surfaced separately via [observePermanentFailureCount] since no amount
     * of waiting for the network ever clears it. */
    @Query("SELECT COUNT(*) FROM pending_sync_operations WHERE isPermanentFailure = 0")
    fun observePendingCount(): Flow<Int>

    /** Rows kept for investigation/manual recovery rather than deleted (spec:
     * "do not silently delete the pending operation") — drives the distinct
     * "Sync Error" recovery affordance ([com.emfitsolutions.gopreach.data.sync
     * .SyncStatusCenter.permanentFailureCount]). */
    @Query("SELECT COUNT(*) FROM pending_sync_operations WHERE isPermanentFailure = 1")
    fun observePermanentFailureCount(): Flow<Int>

    @Delete
    suspend fun remove(operation: PendingSyncOperationEntity)

    /** Called before [enqueue] for a given document so at most one pending
     * operation per document ever sits in the queue at a time — the latest
     * local edit supersedes any earlier still-unsynced one for the same
     * document, rather than piling up duplicate rows (there's no unique
     * constraint on collectionPath+documentId, so without this an
     * [OnConflictStrategy.REPLACE] on the autogenerated `id` alone does
     * nothing to prevent that). Deliberately unconditional (even a row
     * already marked [PendingSyncOperationEntity.isPermanentFailure] gets
     * cleared) — a fresh edit is a deliberate new attempt at this document
     * and deserves its own fair retry, not to inherit a previous attempt's
     * permanent-failure verdict forever. */
    @Query("DELETE FROM pending_sync_operations WHERE collectionPath = :collectionPath AND documentId = :documentId")
    suspend fun removeForDocument(collectionPath: String, documentId: String)

    @Query("UPDATE pending_sync_operations SET retryCount = retryCount + 1, lastError = :error WHERE id = :id")
    suspend fun recordFailure(id: Long, error: String)

    /** A transient failure becomes this once [SyncWorker][com.emfitsolutions
     * .gopreach.data.sync.SyncWorker] classifies the error as permanent
     * (bad data, a security-rules rejection, an invalid path, ...) —
     * excluded from every future retry attempt by [getAllPending], but never
     * deleted. */
    @Query("UPDATE pending_sync_operations SET retryCount = retryCount + 1, lastError = :error, isPermanentFailure = 1 WHERE id = :id")
    suspend fun markPermanentFailure(id: Long, error: String)

    /** Bug fix — a permanent failure previously had no user-facing recovery
     * at all: [SyncStatusCenter][com.emfitsolutions.gopreach.data.sync
     * .SyncStatusCenter] surfaced "Sync Error", but nothing in the app ever
     * showed *which* record failed or *why*, and there was no way back into
     * [getAllPending]'s retry loop short of editing the record again (which
     * only works if the Publisher happens to touch that exact record). This
     * is what a "Retry" action on that error actually needs to see. */
    @Query("SELECT * FROM pending_sync_operations WHERE isPermanentFailure = 1 ORDER BY createdAt ASC")
    fun observePermanentFailures(): Flow<List<PendingSyncOperationEntity>>

    /** The other half of that same fix — an explicit "Retry" puts the row
     * back into [getAllPending]'s normal retry loop (e.g. the Publisher's
     * congregation/permissions changed since, or the original rejection was
     * actually transient and misclassified); it does not reset [retryCount]
     * or [lastError], so the history of what happened is never lost. */
    @Query("UPDATE pending_sync_operations SET isPermanentFailure = 0 WHERE id = :id")
    suspend fun retryPermanentFailure(id: Long)

    /** Same as [retryPermanentFailure] for every permanently-failed row at
     * once — what "Sync to Server" does so one tap re-attempts everything. */
    @Query("UPDATE pending_sync_operations SET isPermanentFailure = 0 WHERE isPermanentFailure = 1")
    suspend fun retryAllPermanentFailures()
}
